//issue

export const REQUEST_ISSUES_GH = 'REQUEST_ISSUES_GH';
export const RECEIVE_ISSUES_SUCCESS_GH = 'RECEIVE_ISSUES_SUCCESS_GH';
export const RECEIVE_ISSUES_ERROR_GH = 'RECEIVE_ISSUES_ERROR_GH';

export const REQUEST_ISSUES = 'REQUEST_ISSUES';
export const RECEIVE_ISSUES_SUCCESS = 'RECEIVE_ISSUES_SUCCESS';
export const RECEIVE_ISSUES_ERROR = 'RECEIVE_ISSUES_ERROR';
export const SAVE_ISSUES = 'SAVE_ISSUES';
export const SAVE_ISSUES_SUCCESS = 'SAVE_ISSUES_SUCCESS';
export const SAVE_ISSUES_ERROR = 'SAVE_ISSUES_ERROR';


// login

export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';
export const SET_LOGIN_USER = 'SET_LOGIN_USER';
export const UPSERT_USER = 'UPSERT_USER';


// vote

export const REQUEST_ISSUE_BY_ID = 'REQUEST_ISSUE_BY_ID';
export const REQUEST_ISSUE_BY_ID_SUCCESS = 'REQUEST_ISSUE_BY_ID_SUCCESS';
export const REQUEST_ISSUE_BY_ID_ERROR = 'REQUEST_ISSUE_BY_ID_ERROR';
