// issue
export const REQUEST_ISSUES_GH = 'REQUEST_ISSUES_GH';
export const RECEIVE_ISSUES_SUCCESS_GH = 'RECEIVE_ISSUES_SUCCESS_GH';
export const RECEIVE_ISSUES_ERROR_GH = 'RECEIVE_ISSUES_ERROR_GH';

// login
export const USER_LOGIN_PANOPTES = 'USER_LOGIN_PANOPTES';
export const USER_LOGIN_FIREBASE = 'USER_LOGIN_FIREBASE';
export const USER_LOGOUT = 'USER_LOGOUT';

// uservotes
export const USERVOTES_ADD = 'USERVOTES_ADD';
export const USERVOTES_REMOVE = 'USERVOTES_REMOVE';

// vote
export const UPDATE_VOTE_COUNT = 'UPDATE_VOTE_COUNT';
