//issue

export const REQUEST_ISSUES_GH = 'REQUEST_ISSUES_GH';
export const RECEIVE_ISSUES_SUCCESS_GH = 'RECEIVE_ISSUES_SUCCESS_GH';
export const RECEIVE_ISSUES_ERROR_GH = 'RECEIVE_ISSUES_ERROR_GH';

export const REQUEST_ISSUES = 'REQUEST_ISSUES';
export const RECEIVE_ISSUES_SUCCESS = 'RECEIVE_ISSUES_SUCCESS';
export const RECEIVE_ISSUES_ERROR = 'RECEIVE_ISSUES_ERROR';
export const SAVE_ISSUES = 'SAVE_ISSUES';
export const SAVE_ISSUES_SUCCESS = 'SAVE_ISSUES_SUCCESS';
export const SAVE_ISSUES_ERROR = 'SAVE_ISSUES_ERROR';


// login

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

// uservotes
export const USERVOTES_ADD = 'USERVOTES_ADD';
export const USERVOTES_REMOVE = 'USERVOTES_REMOVE';

// vote

export const REQUEST_ISSUE_BY_ID = 'REQUEST_ISSUE_BY_ID';
export const REQUEST_ISSUE_BY_ID_SUCCESS = 'REQUEST_ISSUE_BY_ID_SUCCESS';
export const REQUEST_ISSUE_BY_ID_ERROR = 'REQUEST_ISSUE_BY_ID_ERROR';
export const UPDATE_VOTE_COUNT = 'UPDATE_VOTE_COUNT';
